name: push-code

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
